version = 1

test_patterns = ["tests/**"]

exclude_patterns = ["config/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "es-modules"
  environment = [
    "browser",
    "nodejs",
    "jest"
  ]
  plugins = ["vue"]

[[transformers]]
name = "prettier"
enabled = true
