name: 'Pubish Zeal Package'

on:
  push:
    branches:
      - master

jobs:
  bump-package-version:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Import GPG key
        id: import_gpg_sign_commits
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.SPOCK1966_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.SPOCK1966_GPG_KEY_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Bump Version
        env:
          auth_token: ${{ secrets.SPOCK_PAT }}
        run: |
          git config --global user.email "spock1966@deepsource.io"
          git config --global user.name "spock1966"
          npm version patch
          git push

      - name: Temp disable "private"
        run: sed '/private/ s/true/false/' -i package.json

      - name: Install Yarn"
        run: yarn

      - name: Test And Build Library Icons
        id: build
        run: |
          yarn test:unit && yarn build-lib-icons

  publish-zeal-package:
    runs-on: ubuntu-latest
    needs: bump-package-version
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Publish Package
        run: npm publish
