name: 'Pubish Zeal Package'

on:
  push:
    branches:
      - master

jobs:
  bump-package-version:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Import GPG key
        id: import_gpg_sign_commits
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.SPOCK_GPG_KEY }}
          passphrase: ${{ secrets.SPOCK_GPG_KEY_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Bump Version
        run: |
          git config --global user.email "bot@deepsource.io"
          git config --global user.name "deepsourcebot"
          npm version patch

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEEPSOURCE_BOT_TOKEN }}
          branch: ${{ github.ref }}

      - name: Install Yarn"
        run: yarn

      - name: Test And Build Library Icons
        id: build
        run: |
          yarn test:unit && yarn build-lib-icons

  publish-zeal-package:
    runs-on: ubuntu-latest
    needs: bump-package-version
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Temp disable "private"
        run: sed '/private/ s/true/false/' -i package.json

      - name: Publish Package
        run: npm publish
