name: 'Pubish Zeal Package'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'

jobs:
  bump-package-version:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEEPSOURCE_BOT_TOKEN }}
          
      - name: Import GPG key
        id: import_gpg_sign_commits
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.SPOCK_GPG_KEY }}
          passphrase: ${{ secrets.SPOCK_GPG_KEY_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Bump Version
        run: |
          git config --global user.email "bot@deepsource.io"
          git config --global user.name "deepsourcebot"
          npm version patch
          git push
          
      - name: Install Yarn
        run: yarn

      - name: Test And Build Library Icons
        id: build
        run: |
          yarn test:unit && yarn build-lib-icons

  publish-zeal-package:
    runs-on: ubuntu-latest
    needs: bump-package-version
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: git pull origin master

      - name: Temp disable "private"
        run: sed '/private/ s/true/false/' -i package.json
        
      - name: Publish Zeal Package
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@deepsourcelabs'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DEEPSOURCE_BOT_TOKEN }}
        
      - name: Notify Release
        uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with: 
         status: ${{ job.status }}
         if: always()
         channel: '@Shruddha'
