name: 'Pubish Zeal Package'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'yarn.lock'

jobs:
  bump-package-version:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Import GPG key
        id: import_gpg_sign_commits
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.SPOCK_GPG_KEY }}
          passphrase: ${{ secrets.SPOCK_GPG_KEY_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Bump Version
        run: |
          git config --global user.email "bot@deepsource.io"
          git config --global user.name "deepsourcebot"
          npm version patch
          git push
          
      - name: Install Yarn
        run: yarn

      - name: Test
        run: yarn test:unit

  publish-zeal-package:
    runs-on: ubuntu-latest
    needs: bump-package-version
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: git pull origin master

      - name: Temp disable "private"
        run: sed '/private/ s/true/false/' -i package.json
        
      - name: Install Packages
        run: yarn
        
      - name: Build Library Icons
        run: yarn build-lib-icons
        
      - name: Publish Zeal Package
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DEEPSOURCE_BOT_TOKEN }}
